server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api.customer
  datasource:
    driveClassName: org.h2.Driver
    url: jdbc:h2:mem:integrador
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  properties:
    hibernate:
      format_sql: true
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


